# Training configuration for ResNet on CIFAR-10
dataset:
  name: cifar10
  train_split: train
  val_split: test
  num_workers: 4
  batch_size: 128
  transforms:
    train:
      - name: RandomCrop
        params:
          size: 32
          padding: 4
      - name: RandomHorizontalFlip
        params:
          p: 0.5
      - name: ToTensor
      - name: Normalize
        params:
          mean: [0.4914, 0.4822, 0.4465]
          std: [0.2023, 0.1994, 0.2010]
    val:
      - name: ToTensor
      - name: Normalize
        params:
          mean: [0.4914, 0.4822, 0.4465]
          std: [0.2023, 0.1994, 0.2010]

model:
  name: resnet18
  num_classes: 10

optimizer:
  name: SGD
  params:
    lr: 0.1
    momentum: 0.9
    weight_decay: 5e-4

scheduler:
  name: MultiStepLR
  params:
    milestones: [150, 250]
    gamma: 0.1

train:
  epochs: 350
  save_dir: ./checkpoints/
