
# Original paper: https://arxiv.org/abs/1512.03385

config:
  dataset_path: data/tiny-imagenet-200/train
  transform: base_transform
  model: ResNet18

  train:
    epochs: 5
    batch_size: 32
    transform: base_transform
    
    num_workers: 4
    device: cuda
    # save_dir: ./checkpoints/

    optimizer:
      name: SGD
      lr: 0.1
      momentum: 0.9
      weight_decay: 5e-4

    scheduler:
      name: MultiStepLR
      milestones: [150, 250]
      gamma: 0.1


