
# Original paper: https://arxiv.org/abs/1512.03385

config:
  device: cuda

  transform: base_transform
  dataset_path: data/tiny-imagenet-200/train
  batch_size: 32
  num_workers: 4

  model: ResNet18
  
  loss_fn: CrossEntropyLoss
  optimizer:
    name: SGD
    lr: 0.001
    momentum: 0.9
    weight_decay: 5e-4

  scheduler:
    name: MultiStepLR
    milestones: [150, 250]
    gamma: 0.1

  epochs: 5

  debug: false

