
# Original paper: https://arxiv.org/abs/1512.03385

config:
  dataset: tiny-imagenet-200
  model: resnet18

  train:
    epochs: 350
    batch_size: 128
    transform: base_transform
    
    num_workers: 4
    device: cuda
    # save_dir: ./checkpoints/

    optimizer:
      name: SGD
      params:
        lr: 0.1
        momentum: 0.9
        weight_decay: 5e-4

    scheduler:
      name: MultiStepLR
      params:
        milestones: [150, 250]
        gamma: 0.1


